scripts/ddlm_validate: tests/cases/ddlm_validate_020.inp data_unknown: NOTE, data item '_[local]_category.rest_item' was not found in the provided dictionaries.
scripts/ddlm_validate: tests/cases/ddlm_validate_020.inp data_unknown: NOTE, data item '_category.next_item' was not found in the provided dictionaries.
