scripts/ddlm_validate: tests/cases/ddlm_validate_022.inp data_proper_unknown: NOTE, definition of the '_category.next_item' data item was not found in the provided dictionaries.
scripts/ddlm_validate: tests/cases/ddlm_validate_022.inp data_bad_unknown: NOTE, definition of the '_category._[local]_extra_underscore' data item was not found in the provided dictionaries.
scripts/ddlm_validate: tests/cases/ddlm_validate_022.inp data_bad_unknown: NOTE, definition of the '_category.incorrect_[local]_placement' data item was not found in the provided dictionaries.
