scripts/ddlm_validate: tests/cases/ddlm_validate_022.inp data_unknown: WARNING, data item '_category.next_item' was not found in the provided dictionaries.
