scripts/ddlm_validate: tests/cases/ddlm_validate_020.inp data_unknown: NOTE, definition of the '_[local]_category.rest_item' data item was not found in the provided dictionaries.
scripts/ddlm_validate: tests/cases/ddlm_validate_020.inp data_unknown: NOTE, definition of the '_category.next_item' data item was not found in the provided dictionaries.
